substitutions:
  name: esphome-web-04dfa8
  friendly_name: HiFi-ESP32-S3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.7.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

# Enable Home Assistant API
api:

psram:
  mode: octal
  speed: 80MHz
  
i2s_audio:
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO14

media_player:
  - platform: i2s_audio
    name: HiFi Mediaplayer
    id: hifi_mediaplayer
    dac_type: external
    i2s_dout_pin: GPIO16

    on_announcement:
      - light.turn_on:
          id: rgb_front_led
          blue: 100%
          red: 0%
          green: 100%
          brightness: 50%

      - wait_until:
          not:
            media_player.is_announcing:

      - light.turn_off:
          id: rgb_front_led

### RGB light config  (if installed)
light:
  - platform: esp32_rmt_led_strip
    id: rgb_front_led
    name: "${friendly_name} LED"
    rgb_order: GRB
    pin: GPIO9
    num_leds: 1
    chipset: ws2812
    default_transition_length: 0s

### IR reader config  (if installed). Add your own IR codes as needed
remote_receiver:
  pin: 
    number: GPIO7
    inverted: true
    mode:
      input: true
  dump: all

button:
  - platform: restart
    id: restart_btn
    name: "${friendly_name} REBOOT"