substitutions:
  name: esphome-web-ed47ac
  friendly_name: loud-esp32

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    priority: 800
    then:
    - media_player.volume_set:
        id: esp32_audio
        volume: 70%

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

psram:
  mode: octal
  speed: 80MHz

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

switch:
  - platform: gpio
    id: speaker_switch
    icon: "mdi:speaker"
    pin:
      number: GPIO13

media_player:
  - platform: i2s_audio
    name: $friendly_name
    id: esp32_audio
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: stereo
    on_announcement:
      - logger.log: "Announcement started"
      - switch.turn_on:
          id: speaker_switch
    on_play:
      - logger.log: "Playback started"
      - switch.turn_on:
          id: speaker_switch 
    on_pause:
      - logger.log: "Playback paused"
    on_idle:
      - logger.log: "Playback ended"
      - switch.turn_off:
          id: speaker_switch

button:
  - platform: restart
    id: restart_btn
    name: "${friendly_name} REBOOT"