substitutions:
  name: esp32-s3-test
  friendly_name: ESP32-S3-Solo Media Player

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: Sonocotta.ESP32-S3-Solo
    version: '1.0'
  name_add_mac_suffix: false
  on_boot:
    priority: 800
    then:
    - media_player.volume_set:
        id: esp32s3solo
        volume: 50%

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino


# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

psram:
  mode: octal
  speed: 80MHz
  
i2s_audio:
  i2s_lrclk_pin: GPIO16
  i2s_bclk_pin: GPIO10

media_player:
  - platform: i2s_audio
    id: esp32s3solo
    name: $friendly_name
    dac_type: external
    i2s_dout_pin: GPIO44
    mode: stereo